export const getTrackingQuestions = async () => {
  await Promise.resolve();
  return [
    {
      id: 'f1234',
      groupId: '',
      title: 'Did you have a panic attack today?',
      priority: 0,
      type: 'options',
      createdAt: Date.now(),
      expiryDate: null,
      notes: 'What happened?',
      status: 'live',
      settings: {
        type: 'lightswitch',
        calculation: 'count',
        default: [],
      },
    },
    {
      id: 'c1234',
      groupId: '',
      title: 'Paracetemol?',
      priority: 0,
      type: 'options',
      createdAt: Date.now(),
      expiryDate: null,
      notes: true,
      status: 'live',
      settings: {
        type: 'checkbox',
        calculation: '',
        default: [],
        options: ['9am', '11am', '3pm'],
      },
    },
    {
      id: 'd1234',
      groupId: '',
      title: 'How is your mood?',
      priority: 0,
      type: 'options',
      createdAt: Date.now(),
      expiryDate: null,
      notes: true,
      status: 'live',
      settings: {
        type: 'select',
        calculation: '',
        default: [],
        options: ['Happy', 'Sad', 'Aloof'],
      },
    },
    {
      id: '1234',
      groupId: '4321',
      title: 'How did you sleep?',
      priority: 0,
      type: 'number',
      createdAt: Date.now(),
      expiryDate: null,
      notes: true,
      status: 'draft',
      settings: { type: 'star', calculation: 'average', default: null },
    },
    {
      id: 'a1234',
      groupId: '4321',
      title: 'How many hours did you sleep for?',
      priority: 0,
      type: 'number',
      createdAt: Date.now(),
      expiryDate: null,
      notes: false,
      status: 'draft',
      settings: { type: 'number', calculation: 'average', default: null },
    },
    {
      id: 'b1234',
      groupId: '',
      title: 'How far did you run today? (km)',
      priority: 0,
      type: 'number',
      createdAt: Date.now(),
      expiryDate: null,
      notes: false,
      status: 'draft',
      settings: { type: 'number', calculation: 'total', default: null },
    },
  ];
};
